### ISSUE TITLE
Failed to parse json,  Unexpected token u

### ISSUE THREAD

**Issue by sugerdear** [randyliu/json2pb#1]
我用你的demo里的proto和json文件，结果报错如下：Failed to parse json, Unexpected token u

**Comment by randyliu** [comment]
这个错误出现在空参数的情况下， 已经修改代码对这种情况进行报错。 另外我在windows10和centos7下分别用node 4.4.4和node 4.2.6对example进行测试并没有发现错误。 感谢您提出宝贵意见。
