### ISSUE TITLE
还是报错，我通过npm安装的

### ISSUE THREAD

**Issue by sugerdear** [randyliu/json2pb#2]
[root@vagrant-centos65 pmconf_bak]# json2pb -ptest.proto -mpb.json

/usr/lib/node_modules/json2pb/bin/json2pb:79
function* main(argv) {
        ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
[root@vagrant-centos65 pmconf_bak]# cat test.proto 
syntax = "proto3";
message motion_row {
    int32 motion_id = 1;
    string name = 2;
    repeated string privileges = 3;
    string type = 4;
    string category = 5;
}

message motion {
    repeated motion_row rows = 1;
}[root@vagrant-centos65 pmconf_bak]# cat pb.json 
{"rows":[{"motion_id":11001,"name":"","privileges":["owner","admin","user","guest"],"type":"","category":""},{"motion_id":11002,"name":"","privileges":["owner","admin","user","guest"],"type":"","category":""}]}

**Comment by randyliu** [comment]
-m参数应该指定json对象的类型是那个message， 正确的命令是json2pb -ptest.proto **-mmotion** pb.json。
如果你用的是最新的版本， 不指定输入文件， 会报如下错误。
D:\github\json2pb\example>json2pb -ptest.proto -mpb.json
Missing required argument: "files"
Usage: json2pb [options] files

Use json2pb --help for a list of options

**Comment by sugerdear** [comment]
[root@vagrant-centos65 pmconf_bak]# json2pb -ptest.proto -mmotion pb.json -o afdas.fdsafads

/usr/lib/node_modules/json2pb/bin/json2pb:79
function* main(argv) {
        ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

还是不行，而且查看帮助都查看不了

**Comment by randyliu** [comment]
你先npm install -g json2pb更新下， 然后把-o参数放到输入文件前面。
json2pb -ptest.proto -mmotion  -o afdas.fdsafads pb.json
Usage: json2pb [options] files
Options:
  -h, --help                   Display this information.
  -v, --version                Print the compiler version.
  -I, --include                Specify the directory in which to search for imports.
  -d, --dependency             Output a rule suitable for make describing the dependencies of the main source file.
  -j, --join                   Output joined file.
  -o, --output                 Encode to the file.
  -m, --message                Set the message to be built.
  -p, --proto                  Specify the protobuf's .proto file.

**Comment by sugerdear** [comment]
[root@vagrant-centos65 pmconf_bak]# npm install -g json2pb
npm http GET https://registry.npmjs.org/json2pb
npm http 304 https://registry.npmjs.org/json2pb
npm http GET https://registry.npmjs.org/co/4.6.0
npm http GET https://registry.npmjs.org/co-fs/1.2.0
npm http GET https://registry.npmjs.org/protobufjs/5.0.1
npm http GET https://registry.npmjs.org/posix-getopt/1.2.0
npm http 304 https://registry.npmjs.org/co-fs/1.2.0
npm http 304 https://registry.npmjs.org/posix-getopt/1.2.0
npm http 304 https://registry.npmjs.org/protobufjs/5.0.1
npm http 304 https://registry.npmjs.org/co/4.6.0
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"v0.10.42","npm":"1.3.6"})
npm http GET https://registry.npmjs.org/thunkify/0.0.1
npm http GET https://registry.npmjs.org/co-from-stream/0.0.0
npm http GET https://registry.npmjs.org/ascli
npm http GET https://registry.npmjs.org/bytebuffer
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/yargs
npm http 304 https://registry.npmjs.org/thunkify/0.0.1
npm http 304 https://registry.npmjs.org/co-from-stream/0.0.0
npm http 304 https://registry.npmjs.org/bytebuffer
npm http 304 https://registry.npmjs.org/ascli
npm http 304 https://registry.npmjs.org/yargs
npm http 304 https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/co-read/0.0.1
npm http GET https://registry.npmjs.org/inflight
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/once
npm http GET https://registry.npmjs.org/path-is-absolute
npm http GET https://registry.npmjs.org/colour
npm http GET https://registry.npmjs.org/optjs
npm http GET https://registry.npmjs.org/camelcase
npm http GET https://registry.npmjs.org/cliui
npm http GET https://registry.npmjs.org/decamelize
npm http GET https://registry.npmjs.org/os-locale
npm http GET https://registry.npmjs.org/string-width
npm http GET https://registry.npmjs.org/window-size
npm http GET https://registry.npmjs.org/y18n
npm http GET https://registry.npmjs.org/long
npm http 304 https://registry.npmjs.org/inflight
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/path-is-absolute
npm http 304 https://registry.npmjs.org/camelcase
npm http GET https://registry.npmjs.org/wrappy
npm http GET https://registry.npmjs.org/brace-expansion
npm http 304 https://registry.npmjs.org/co-read/0.0.1
npm http 304 https://registry.npmjs.org/cliui
npm http 304 https://registry.npmjs.org/decamelize
npm http 304 https://registry.npmjs.org/os-locale
npm http 304 https://registry.npmjs.org/string-width
npm http 304 https://registry.npmjs.org/window-size
npm http 304 https://registry.npmjs.org/colour
npm http 304 https://registry.npmjs.org/y18n
npm http 304 https://registry.npmjs.org/optjs
npm http 304 https://registry.npmjs.org/wrappy
npm http 304 https://registry.npmjs.org/brace-expansion
npm http GET https://registry.npmjs.org/code-point-at
npm http GET https://registry.npmjs.org/is-fullwidth-code-point
npm http GET https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/lcid
npm http GET https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/wrap-ansi
npm http GET https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/concat-map/0.0.1
npm http 304 https://registry.npmjs.org/is-fullwidth-code-point
npm http 304 https://registry.npmjs.org/lcid
npm http 304 https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/invert-kv
npm http 304 https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/wrap-ansi
npm http 304 https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/invert-kv
npm http 304 https://registry.npmjs.org/code-point-at
npm http GET https://registry.npmjs.org/number-is-nan
npm http 304 https://registry.npmjs.org/concat-map/0.0.1
npm http 304 https://registry.npmjs.org/ansi-regex
npm http 200 https://registry.npmjs.org/number-is-nan
npm http 304 https://registry.npmjs.org/long
/usr/bin/json2pb -> /usr/lib/node_modules/json2pb/bin/json2pb
npm WARN unmet dependency /usr/lib/node_modules/block-stream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/fstream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/fstream-ignore requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/fstream-npm requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/glob requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/npmconf requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/tar requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
json2pb@1.1.20 /usr/lib/node_modules/json2pb
├── co@4.6.0
├── posix-getopt@1.2.0
├── co-fs@1.2.0 (thunkify@0.0.1, co-from-stream@0.0.0)
└── protobufjs@5.0.1 (ascli@1.0.0, glob@5.0.15, bytebuffer@5.0.1, yargs@3.32.0)
[root@vagrant-centos65 pmconf_bak]# 
[root@vagrant-centos65 pmconf_bak]# 
[root@vagrant-centos65 pmconf_bak]# json2pb -ptest.proto -mmotion -o afdas.fdsafads pb.json

/usr/lib/node_modules/json2pb/bin/json2pb:79
function* main(argv) {
        ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

报错依然存在

**Comment by sugerdear** [comment]
这个是语法错吧，或者是你本地开发环境和我的不一样，我是centos6.5

**Comment by randyliu** [comment]
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"v0.10.42","npm":"1.3.6"})

升级下node， 库里面用的都是es6的generator。

**Comment by sugerdear** [comment]
好，提两个建议吧：
1、环境依赖写的清楚些
2、可以根据json自动生成proto文件，比如说指定json文件，会输出proto文件和pb文件

**Comment by randyliu** [comment]
非常感谢您的建议
1、已经把引擎版本写到package.json文件里面了。
2、确实写过一个工具输入若干json对象输出proto文件的， 可是大家并不喜欢这么用， 我也很无奈啊……

**Comment by sugerdear** [comment]
[root@vagrant-centos65 pmconf_bak]# node -v
v0.12.14
[root@vagrant-centos65 pmconf_bak]# json2pb -h
/root/.nvm/v0.12.14/lib/node_modules/json2pb/bin/json2pb:79
function* main(argv) {
        ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by sugerdear** [comment]
可以了。

**Comment by sugerdear** [comment]
2、确实写过一个工具输入若干json对象输出proto文件的， 可是大家并不喜欢这么用， 我也很无奈啊……
>>工具可以都支持，可以通过参数随便选择，哈哈
